import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Sketch from "./sketch";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gautam Chebrolu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.canvas}>
          <Sketch />
        </div>
      </header>
      <main>
        <section className={styles.name}>
          <h1 className={styles.center}>Gautam Chebrolu</h1>
          <a href="mailto:varpra1@gmail.com">varpra1@gmail.com</a>
        </section>
      </main>
    </div>
  );
}
